title: Ray Coden Mercurius
logo: /assets/img/NA.jpg
description: Coden's personal website
show_downloads: false
google_analytics: UA-195366952-1
theme: jekyll-theme-minimal

author: Ray Coden Mercurius
email: coden.m@hotmail.com


social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  LinkedIn: https://www.linkedin.com/in/shirley-shuocheng-zhang/
  GitHub: https://github.com/shirleyzhang2
