title: Ray Coden Mercurius
logo: /assets/img/logo3.jpg
description: Coden's personal website
show_downloads: false
google_analytics: UA-195366952-1
theme: jekyll-theme-minimal

author: Ray Coden Mercurius
email: coden.m@hotmail.com


social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  GitHub: https://github.com/Ceudan
  Google Scholar: https://scholar.google.ca/citations?view_op=list_works&hl=en&user=QN2jzVEAAAAJ
